dubbo:
  application:
    name: dubbo-provider2
  scan:
    base-packages: com.example.provider.service
  registry:
    address: localhost:2181
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 20881
#  monitor:
#    protocol: register
  consumer:
    check: false
    timeout: 3000

server:
  port: 9002

spring:
  redis:
    host: localhost
    pool: 6379
    database: 0
    jedis:
      pool:
        min-idle: 10
        max-idle: 25
        max-wait: -1
        max-active: 100
  application:
    name: provider2